# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-06 03:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(max_length=150, verbose_name='Last name')),
                ('firstname', models.CharField(max_length=150, verbose_name='First name')),
            ],
            options={
                'verbose_name_plural': 'Artists',
                'verbose_name': 'Artist',
            },
        ),
        migrations.CreateModel(
            name='Mural',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_id', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Import identifier')),
                ('image', models.ImageField(blank=True, null=True, upload_to='murals/', verbose_name='Image')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Year')),
                ('address', models.CharField(max_length=200, verbose_name='Address')),
                ('address_2', models.CharField(blank=True, max_length=200, null=True, verbose_name='Address Line 2')),
                ('zip_code', models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='ZIP Code')),
                ('city', models.CharField(db_index=True, max_length=200, verbose_name='City')),
                ('country', models.CharField(db_index=True, max_length=200, verbose_name='Country')),
                ('latitude', models.DecimalField(db_index=True, decimal_places=25, max_digits=27, verbose_name='Latitude')),
                ('longitude', models.DecimalField(db_index=True, decimal_places=24, max_digits=27, verbose_name='Latitude')),
                ('artists', models.ManyToManyField(to='mural.Artist', verbose_name='Artists')),
            ],
            options={
                'verbose_name_plural': 'Murals',
                'ordering': ['-year'],
                'verbose_name': 'Mural',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
            ],
            options={
                'verbose_name_plural': 'Organizations',
                'verbose_name': 'Organization',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
            ],
            options={
                'verbose_name_plural': 'Organizations',
                'verbose_name': 'Program',
            },
        ),
        migrations.AddField(
            model_name='mural',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mural.Organization', verbose_name='Organization'),
        ),
        migrations.AddField(
            model_name='mural',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mural.Program', verbose_name='Program'),
        ),
    ]
