language: python
python:
  - "3.6"
before_install:
  - nvm install 7.6
  - nvm use 7.6
install:
  - make install
  - npm install
script:
  - make coverage
  - bash <(curl -s https://codecov.io/bash) -F py
  - npm test
  - bash <(curl -s https://codecov.io/bash) -F js
