"""
    Development upload sets
    =======================

    This module defines development upload sets that will be used to serve files or images during
    developments only.

"""

from flask_uploads import IMAGES
from flask_uploads import UploadSet


# During developments thumbnails generated by Flask-Resize will be served using an upload set.
thumbnails = UploadSet('thumbnails', IMAGES)
