"""Created initial mural tables

Revision ID: 89854dc4ec9c
Revises:
Create Date: 2017-06-04 21:11:12.543941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89854dc4ec9c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artist',
    sa.Column('lastname', sa.Unicode(length=124), nullable=False),
    sa.Column('firstname', sa.Unicode(length=124), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organization',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(length=124), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('program',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(length=124), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mural',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('import_id', sa.String(length=64), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('program_id', sa.Integer(), nullable=True),
    sa.Column('image', sa.Unicode(length=255), nullable=True),
    sa.Column('year', sa.SmallInteger(), nullable=True),
    sa.Column('address', sa.Unicode(length=124), nullable=True),
    sa.Column('address_2', sa.Unicode(length=124), nullable=True),
    sa.Column('zip_code', sa.String(length=20), nullable=True),
    sa.Column('city', sa.Unicode(length=124), nullable=True),
    sa.Column('country', sa.Unicode(length=124), nullable=True),
    sa.Column('latitude', sa.Numeric(), nullable=True),
    sa.Column('longitude', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['program_id'], ['program.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mural_city'), 'mural', ['city'], unique=False)
    op.create_index(op.f('ix_mural_country'), 'mural', ['country'], unique=False)
    op.create_index(op.f('ix_mural_import_id'), 'mural', ['import_id'], unique=True)
    op.create_index(op.f('ix_mural_latitude'), 'mural', ['latitude'], unique=False)
    op.create_index(op.f('ix_mural_longitude'), 'mural', ['longitude'], unique=False)
    op.create_index(op.f('ix_mural_zip_code'), 'mural', ['zip_code'], unique=False)
    op.create_table('mural_artist',
    sa.Column('artist_id', sa.Integer(), nullable=True),
    sa.Column('mural_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['artist.id'], ),
    sa.ForeignKeyConstraint(['mural_id'], ['mural.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mural_artist')
    op.drop_index(op.f('ix_mural_zip_code'), table_name='mural')
    op.drop_index(op.f('ix_mural_longitude'), table_name='mural')
    op.drop_index(op.f('ix_mural_latitude'), table_name='mural')
    op.drop_index(op.f('ix_mural_import_id'), table_name='mural')
    op.drop_index(op.f('ix_mural_country'), table_name='mural')
    op.drop_index(op.f('ix_mural_city'), table_name='mural')
    op.drop_table('mural')
    op.drop_table('program')
    op.drop_table('organization')
    op.drop_table('artist')
    # ### end Alembic commands ###
